version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: 'rabbitmq'
    environment:
      INSERTION_QUEUE: insertion.queue
      VALIDATION_QUEUE: validation.queue
      NUMBER_OF_VALIDATION_CONSUMERS: 1
      RESPONSE_EXCHANGE: response.exchange
      RESPONSE_ROUTING_KEY: response.routing.key
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: /
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672"


