FROM openjdk:17-jdk
EXPOSE 8011
VOLUME /tmp
COPY apiEncryptionKey.jks-storepass apiEncryptionKey.jks-storepass
COPY target/config-server.jar config-server.jar
ENTRYPOINT ["java","-jar","/config-server.jar"]